### ISSUE TITLE
Tests/Install/TravisCI failing with python 3.6.3. Works with Python 3.6.2. 

### ISSUE THREAD

**Issue by nkeilar** [mrjbq7/ta-lib#158] opened 2017-10-05 20:44 UTC
```
============================= test session starts ==============================
platform linux -- Python 3.6.3+, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
rootdir: /home/travis/build/Company/project-name, inifile:
collected 0 items / 1 errors                                                    

==================================== ERRORS ====================================
______________________________ ERROR collecting  _______________________________
../../../virtualenv/python3.6-dev/lib/python3.6/site-packages/py/_error.py:65: in checked_call
    return func(*args, **kwargs)
E   NotADirectoryError: [Errno 20] Not a directory: '/home/travis/build/Company/project-name/ta-lib/bin'

During handling of the above exception, another exception occurred:
../../../virtualenv/python3.6-dev/lib/python3.6/site-packages/py/_path/common.py:372: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
../../../virtualenv/python3.6-dev/lib/python3.6/site-packages/py/_path/common.py:410: in gen
    dirs = self.optsort([p for p in entries
../../../virtualenv/python3.6-dev/lib/python3.6/site-packages/py/_path/common.py:411: in <listcomp>
    if p.check(dir=1) and (rec is None or rec(p))])
../../../virtualenv/python3.6-dev/lib/python3.6/site-packages/_pytest/main.py:723: in _recurse
    if ihook.pytest_ignore_collect(path=path, config=self.config):
../../../virtualenv/python3.6-dev/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py:745: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
../../../virtualenv/python3.6-dev/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py:339: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../virtualenv/python3.6-dev/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py:334: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
../../../virtualenv/python3.6-dev/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py:614: in execute
    res = hook_impl.function(*args)
../../../virtualenv/python3.6-dev/lib/python3.6/site-packages/_pytest/main.py:197: in pytest_ignore_collect
    if _in_venv(path) and not allow_in_venv:
../../../virtualenv/python3.6-dev/lib/python3.6/site-packages/_pytest/main.py:183: in _in_venv
    return any([fname.basename in activates for fname in bindir.listdir()])
../../../virtualenv/python3.6-dev/lib/python3.6/site-packages/py/_path/local.py:382: in listdir
    names = py.error.checked_call(os.listdir, self.strpath)
../../../virtualenv/python3.6-dev/lib/python3.6/site-packages/py/_error.py:85: in checked_call
    raise cls("%s%r" % (func.__name__, args))
E   py.error.ENOTDIR: [Not a directory]: listdir('/home/travis/build/Company/project-name/ta-lib/bin',)
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.26 seconds ============================


The command "pytest" exited with 2.

```

TA-lib Is installed as follows

```
#!/bin/sh
#set -ex
wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
tar -xzvf ta-lib-0.4.0-src.tar.gz
cd ta-lib && ./configure && make && sudo make install
rm -rf ta-lib ta-lib-0.4.0-src.tar.gz
```

**Comment by mrjbq7** [comment] 2017-10-09 03:13
That's confusing to me because I don't understand why it would be running ``pytest``?

And secondly because as far as I know, I've never had a ``bin`` directory in this project.

**Comment by nkeilar** [comment] 2017-10-09 03:23
Hey @mrjbq7, thanks for taking a look at this issue. Basically we've included this in a python project with testing setup on travisci. pytest is the command we have in travis that typically runs our tests, however with Python 3.6.3 it breaks with the above error. 

I guess for some reason talib binary is being installed in a different location to that expected. Or that its looking in the wrong location for the binary after a change in python 3.6.3. 

To be honest it seems odd to me, but thought it may have been something obvious to you. I'll get back to it in due course and report anything extra I find, but its not a high priority for us currently. 

Do you have any issues when running pytest with python 3.6.3?

**Comment by mrjbq7** [comment] 2017-10-09 16:42
Why would this ``bin`` exist?  That's the only way that exception could be generated.  See this code from ``pytest``.  It checks if ``bindir.exists()`` and returns if it doesn't.  So it must somehow exist in your configuration and be a file, not a directory:

https://github.com/pytest-dev/pytest/blob/master/_pytest/main.py#L179

But ``ta-lib`` is distributed without a ``bin`` directory?

```
$ tar xvfz TA-Lib-0.4.10.tar.gz 
x TA-Lib-0.4.10/
x TA-Lib-0.4.10/COPYRIGHT
x TA-Lib-0.4.10/LICENSE
x TA-Lib-0.4.10/PKG-INFO
x TA-Lib-0.4.10/README.md
x TA-Lib-0.4.10/setup.py
x TA-Lib-0.4.10/talib/
x TA-Lib-0.4.10/talib/__init__.py
x TA-Lib-0.4.10/talib/abstract.c
x TA-Lib-0.4.10/talib/abstract.pyx
x TA-Lib-0.4.10/talib/common.c
x TA-Lib-0.4.10/talib/common.pyx
x TA-Lib-0.4.10/talib/deprecated.py
x TA-Lib-0.4.10/talib/func.c
x TA-Lib-0.4.10/talib/func.pyx
x TA-Lib-0.4.10/talib/stream.c
x TA-Lib-0.4.10/talib/stream.pyx
x TA-Lib-0.4.10/talib/test_abstract.py
x TA-Lib-0.4.10/talib/test_data.py
x TA-Lib-0.4.10/talib/test_func.py
x TA-Lib-0.4.10/talib/test_stream.py
```

Without knowing your environment, I couldn't really hazard a guess about why ``bin`` is being created **as a file** or **even at all**...

(I couldn't seem to reproduce your exception on macOS 10.13 and Python 3.6.3 with pytest 3.2.3 and ta-lib 0.4.10...)

**Comment by mrjbq7** [comment] 2022-04-16 17:19
Closing all installation issues, if someone has a specific problem please open a new one.

**Closed by mrjbq7** 2022-04-16 17:19 UTC
