### ISSUE TITLE
unable to install ta-lib

### ISSUE THREAD

**Issue by Sansohasarabjit** [mrjbq7/ta-lib#501] opened 2022-02-18 15:57 UTC

**Comment by Sansohasarabjit** [comment] 2022-02-18 15:57
(new.env) C:\Windows\system32>pip install -i https://pypi.anaconda.org/masdeseiscaracteres/simple ta-lib
WARNING: Ignoring invalid distribution -quests (c:\programdata\anaconda3\envs\new.env\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\envs\new.env\lib\site-packages)
WARNING: Ignoring invalid distribution -equests (c:\programdata\anaconda3\envs\new.env\lib\site-packages)
WARNING: Ignoring invalid distribution -quests (c:\programdata\anaconda3\envs\new.env\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\envs\new.env\lib\site-packages)
WARNING: Ignoring invalid distribution -equests (c:\programdata\anaconda3\envs\new.env\lib\site-packages)
Looking in indexes: https://pypi.anaconda.org/masdeseiscaracteres/simple
ERROR: Could not find a version that satisfies the requirement ta-lib (from versions: none)
ERROR: No matching distribution found for ta-lib
WARNING: Ignoring invalid distribution -quests (c:\programdata\anaconda3\envs\new.env\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\envs\new.env\lib\site-packages)
WARNING: Ignoring invalid distribution -equests (c:\programdata\anaconda3\envs\new.env\lib\site-packages)
WARNING: Ignoring invalid distribution -quests (c:\programdata\anaconda3\envs\new.env\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\envs\new.env\lib\site-packages)
WARNING: Ignoring invalid distribution -equests (c:\programdata\anaconda3\envs\new.env\lib\site-packages)
WARNING: Ignoring invalid distribution -quests (c:\programdata\anaconda3\envs\new.env\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\envs\new.env\lib\site-packages)
WARNING: Ignoring invalid distribution -equests (c:\programdata\anaconda3\envs\new.env\lib\site-packages)

**Comment by trufanov-nok** [comment] 2022-02-18 16:09
I guess it's supposed to work from Anaconda environment and you're trying it from Windows machine.

**Comment by Pierrewan** [comment] 2022-03-05 14:18
I was installed on my Mac M1, When I used Anaconda Jupyter notebook was can't import talib 
<img width="1440" alt="螢幕截圖 2022-03-05 下午9 07 13" src="https://user-images.githubusercontent.com/33239733/156887138-b456bb3e-c777-45d5-9e14-dfb5e6972339.png">
<img width="870" alt="螢幕截圖 2022-03-05 下午9 18 53" src="https://user-images.githubusercontent.com/33239733/156887146-4057e331-eb34-4e41-8e57-47d03b078ff0.png">

**Comment by trufanov-nok** [comment] 2022-03-05 14:53
In a very first line you got `wget: command not found`. It means `wget` (a command line utility for non-interactive download of files from the Web) isn't installed.
Execute
```
!apt-get update
!apt-get install wget
```
beforehand.

**Comment by Pierrewan** [comment] 2022-03-08 08:41
<img width="1440" alt="螢幕截圖 2022-03-08 下午4 39 02" src="https://user-images.githubusercontent.com/33239733/157199707-899bef94-2773-45de-8590-e17ebb3f71ee.png">

**Comment by Pierrewan** [comment] 2022-03-08 08:42
command ont found

**Comment by trufanov-nok** [comment] 2022-03-08 10:26
Ok, I tried it online and realized that current JupyterLite is now coming with Pyolite kernel only, which is not supporting the background processes so ta-lib installation into notebook on jupyter.com is currently not possible.  

But you seems to have an own locally installed Notebook with ipykernel, so it should be able to execute commands in a shell.  

The problem is that your system is Mac, so you need the install instructions for Mac. The `apt` stuff is for Linux machine. I never tried to install TA-Lib on Mac via JupyterNotebook, but I guess it should work. Execute in Notebook (this need to be done only once):
```
!brew install ta-lib
!export TA_INCLUDE_PATH="$(brew --prefix ta-lib)/include"
!export TA_LIBRARY_PATH="$(brew --prefix ta-lib)/lib"
!pip install ta-lib
```
Check if the output is ok. Then restart the Jupyter Notebook and try to import talib module.

**Comment by mrjbq7** [comment] 2022-04-16 17:13
Closing all installation issues, if someone has a specific problem please open a new one.

**Closed by mrjbq7** 2022-04-16 17:13 UTC
